In [1]:
#Numpy

In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [3]:
#Creating Arrays

In [4]:
sample_array=np.array([1,2,3,4])

In [5]:
sample_array

array([1, 2, 3, 4])

In [10]:
sample_array1=np.array([11,22,33,44,55])

In [12]:
sample_array1

array([11, 22, 33, 44, 55])

In [13]:
#2d array(a matrix) with 2 rows and 2 coloumns

In [15]:
sample_array_2=np.array([[1,2],[3,4]])

In [16]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [17]:
sample_array_3=np.array([[11,22],[44,55]])

In [18]:
sample_array_3

array([[11, 22],
       [44, 55]])

In [19]:
# 3D tensor(2 matrices,each with 2 rows and 2 coloumns)

In [21]:
sample_tensor_3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [22]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
sample_tensor_4=np.array([[[42,34],[75,78]],[[55,77],[10,43]]])

In [26]:
sample_tensor_4

array([[[42, 34],
        [75, 78]],

       [[55, 77],
        [10, 43]]])

In [27]:
#Dimensions 

In [28]:
#0-D Array(scalar)  5
#1-D Array(vector)  [1,2,3,4]
#2-D Array(matrix)  (rows,coloumns)
#3-D Array(Tensor)  (page,row,coloumn)

In [29]:
#Array properties

In [31]:
sample_array=np.array([[1,2,3],[4,5,6]])

In [32]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
#Shape

In [35]:
sample_array.shape

(2, 3)

In [36]:
#dimensions

In [37]:
sample_array.ndim

2

In [38]:
#total elements

In [39]:
sample_array.size

6

In [40]:
#data type

In [41]:
sample_array.dtype

dtype('int64')

In [42]:
sample_array5=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [43]:
sample_array5.shape

(2, 2, 2)

In [44]:
sample_array5.ndim

3

In [45]:
sample_array5.size

8

In [46]:
sample_array5.dtype

dtype('int64')

In [47]:
#Special Arrays

In [48]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [58]:
np.arange(1,102,4)

array([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,
        53,  57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101])

In [62]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [64]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [65]:
# Indexing and slicing

In [66]:
sample_array=np.array([10,20,30,40])

In [67]:
sample_array

array([10, 20, 30, 40])

In [68]:
sample_array[0]

np.int64(10)

In [71]:
sample_array[1]

np.int64(20)

In [72]:
sample_array[-1]

np.int64(40)

In [73]:
# Slicing

In [74]:
sample_array[1:3]

array([20, 30])

In [75]:
sample_array[:4]

array([10, 20, 30, 40])

In [76]:
# Array Operations

In [77]:
a=np.array([1,2,3])

In [78]:
b=np.array([4,5,6])

In [79]:
a

array([1, 2, 3])

In [80]:
b

array([4, 5, 6])

In [81]:
a+b

array([5, 7, 9])

In [82]:
a-b

array([-3, -3, -3])

In [83]:
a*b

array([ 4, 10, 18])

In [84]:
a/b

array([0.25, 0.4 , 0.5 ])

In [85]:
x=np.array([12,32,45])
y=np.array([6,16,22])

In [86]:
x+y

array([18, 48, 67])

In [87]:
x-y

array([ 6, 16, 23])

In [88]:
x/y

array([2.        , 2.        , 2.04545455])

In [89]:
x*y

array([ 72, 512, 990])

In [90]:
y-x

array([ -6, -16, -23])

In [91]:
y/x

array([0.5       , 0.5       , 0.48888889])

In [92]:
#Mathematical Functions

In [93]:
sample_array=np.array([1,4,9])

In [94]:
sample_array

array([1, 4, 9])

In [95]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [98]:
sample_array1=np.array([64,121,256])

In [99]:
np.sqrt(sample_array1)

array([ 8., 11., 16.])

In [100]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [101]:
q=np.array([3,5,8])

In [102]:
np.exp(q)

array([  20.08553692,  148.4131591 , 2980.95798704])

In [104]:
np.log(q)

array([1.09861229, 1.60943791, 2.07944154])

In [105]:
w=np.array([4,5,6])

In [106]:
np.log(w)

array([1.38629436, 1.60943791, 1.79175947])

In [107]:
# Statistical Functions

In [108]:
sample_array=np.array([1,2,3,4,5])

In [109]:
sample_array

array([1, 2, 3, 4, 5])

In [110]:
np.mean(sample_array)

np.float64(3.0)

In [111]:
np.median(sample_array)

np.float64(3.0)

In [114]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [115]:
np.min(sample_array)

np.int64(1)

In [116]:
np.max(sample_array)

np.int64(5)

In [117]:
#Reshaping Arrays

In [121]:
sample_array=np.arange(0,6,1)

In [122]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [125]:
reshaped=sample_array.reshape(2,3)

In [126]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [129]:
reshaped.shape

(2, 3)

In [130]:
# Flattening 

In [131]:
sample_array=np.array([[11,22],[33,44]])

In [132]:
sample_array

array([[11, 22],
       [33, 44]])

In [133]:
sample_array.flatten()

array([11, 22, 33, 44])

In [135]:
sample_array4=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [137]:
sample_array4.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [138]:
# joining two arrays

In [139]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [143]:
arr1


array([1, 2, 3])

In [144]:
arr2

array([4, 5, 6])

In [146]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [147]:
np.concat((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [150]:
# Spliting arrays

In [151]:
sample_array=np.array([1,2,3,4])

In [152]:
sample_array

array([1, 2, 3, 4])

In [155]:
np.array_split(sample_array,6)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([], dtype=int64),
 array([], dtype=int64)]

In [156]:
# Random module

In [161]:
np.random.rand(3)       #float values

array([0.60160974, 0.19236182, 0.73083016])

In [162]:
np.random.randint(1,10,5)      #integers values

array([6, 7, 5, 7, 6], dtype=int32)

In [163]:
# Axis Concept

In [164]:
sample_array=np.array([[1,2],[3,4]])

In [165]:
sample_array

array([[1, 2],
       [3, 4]])

In [166]:
# coloumn axis =0
# rows axis=1

In [167]:
np.sum(sample_array,axis=0)

array([4, 6])

In [168]:
np.sum(sample_array,axis=1)

array([3, 7])

In [169]:
# NaN & Missing values

In [170]:
sample_array=np.array([1,np.nan,3])

In [171]:
sample_array

array([ 1., nan,  3.])

In [174]:
np.isnan(sample_array)

array([False,  True, False])

In [2]:
# create two numpy arrays and perform element wise addition substraction muultiplication and modulus operations 

In [4]:
import numpy as np



arr1=np.array([10,20,30])
arr2=np.array([40,50,60])

In [5]:
arr1+arr2

array([50, 70, 90])

In [6]:
arr1-arr2

array([-30, -30, -30])

In [7]:
arr1*arr2

array([ 400, 1000, 1800])

In [8]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [9]:
mod_arr=arr1%arr2

In [10]:
mod_arr

array([10, 20, 30])