Section A — Exception Handling

In [2]:
'''
1. Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError and
TypeError separately, printing an appropriate message for each. Use a finally block to print
'Operation attempted.' regardless of the outcome. Test it with valid numbers, division by zero, and a
string input.
''';

In [3]:
def safe_divide(a, b):
    try:
        result = a / b
        print("Result:", result)

    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")

    except TypeError:
        print("Error: Invalid data type. Please enter numbers only.")

    finally:
        print("Operation attempted.\n")



In [4]:
safe_divide(12,2)

Result: 6.0
Operation attempted.



In [5]:
safe_divide(10,0)

Error: Cannot divide by zero.
Operation attempted.



In [6]:
safe_divide('10','1')

Error: Invalid data type. Please enter numbers only.
Operation attempted.



In [7]:
'''
2. Write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you
define, inheriting from Exception) if age is negative or greater than 120. Catch this exception in a
calling block and print a user-friendly message. Test it with at least 3 different values.
''';

In [8]:

class InvalidAgeError(Exception):
    pass


def validate_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError("Invalid age entered.")
    print("Valid Age:", age)



In [9]:
try:
    validate_age(25)
except InvalidAgeError as a:
    print('error',a)

Valid Age: 25


In [10]:
try:
    validate_age(-10)
except InvalidAgeError as a:
    print('error',a)

error Invalid age entered.


In [11]:
try:
    validate_age(125)
except InvalidAgeError as a:
    print('error',a)

error Invalid age entered.


In [12]:
'''
3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list,
e.g. user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. Handle the following in
a single try block using multiple except clauses:
a) ValueError if the input is not a number.
b) ZeroDivisionError if the input is zero.
c) A generic Exception as a catch-all for anything else.
Print the result if successful, otherwise print which error occurred.''';

In [14]:
user_inputs=['20','xyz','0',None,50]

for i in user_inputs:
    try:
        num=int(i)
        result=100/num
        print('result is ',result)

    except ValueError:
        print('not a number')
    except ZeroDivisionError:
        print('cannot divide by zero')
    except Exception as e:
        print('exception occured is',e)

result is  5.0
not a number
cannot divide by zero
exception occured is int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
result is  2.0


Section B — NumPy

In [13]:
'''
4. Create a 1D NumPy array of integers from 1 to 20. Perform the following:
a) Reshape it into a 4x5 2D array.
b) Print the sum of each row and each column.
c) Extract all elements greater than 10 using boolean indexing.
d) Replace all even numbers in the array with -1

''';

In [14]:
import numpy as np

# Create 1D array from 1 to 20
arr = np.arange(1, 21)
print("Original 1D array:\n", arr)

# a) Reshape into 4x5 array
arr_2d = arr.reshape(4, 5)
print("\nReshaped 4x5 array:\n", arr_2d)

# b) Sum of each row and each column
row_sum = arr_2d.sum(axis=1)
col_sum = arr_2d.sum(axis=0)

print("\nSum of each row:", row_sum)
print("Sum of each column:", col_sum)

# c) Elements greater than 10
greater_than_10 = arr_2d[arr_2d > 10]
print("\nElements greater than 10:", greater_than_10)

# d) Replace even numbers with -1
modified_arr = arr_2d.copy()
modified_arr[modified_arr % 2 == 0] = -1

print("\nArray after replacing even numbers with -1:\n", modified_arr)

Original 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Reshaped 4x5 array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Sum of each row: [15 40 65 90]
Sum of each column: [34 38 42 46 50]

Elements greater than 10: [11 12 13 14 15 16 17 18 19 20]

Array after replacing even numbers with -1:
 [[ 1 -1  3 -1  5]
 [-1  7 -1  9 -1]
 [11 -1 13 -1 15]
 [-1 17 -1 19 -1]]


In [15]:
'''
5. Create two NumPy arrays A and B as shown below and perform:
A = np.array([[1, 2], [3, 4]]) B = np.array([[5, 6], [7, 8]])
a) Element-wise addition, subtraction, and multiplication.
b) Matrix multiplication using np.dot() or the @ operator.
c) Transpose of A.
d) The determinant and inverse of A using np.linalg.

''';

In [16]:
import numpy as np

# Define arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# a) Element-wise operations
addition = A + B
subtraction = A - B
multiplication = A * B

print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)




# c) Transpose of A
transpose_A = A.T
print("\nTranspose of A:\n", transpose_A)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Element-wise Addition:
 [[ 6  8]
 [10 12]]

Element-wise Subtraction:
 [[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]

Transpose of A:
 [[1 3]
 [2 4]]


In [17]:
'''
6. Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint()
(set a seed of 42 for reproducibility). Then:
a) Find the mean, median, standard deviation, min, and max.
b) Sort the array in descending order.
c) Find the indices of the 3 largest values using np.argsort().
d) Normalize the array so all values lie between 0 and 1.
''';

In [17]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Generate array
arr = np.random.randint(1, 101, 15)
print("Original Array:\n", arr)

# a) Statistics
print("\nMean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

# b) Sort in descending order
sorted_desc = np.sort(arr)[::-1]
print("\nSorted (Descending):\n", sorted_desc)

# c) SIMPLE argsort logic (TOP 3 LARGEST VALUES)
sorted_indices = np.argsort(arr)     # ascending order indices
top3_indices = sorted_indices[-3:]   # last 3 = largest values

print("\nIndices of 3 largest values:", top3_indices)
print("Top 3 values:", arr[top3_indices])



Original Array:
 [ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]

Mean: 58.06666666666667
Median: 72.0
Standard Deviation: 31.4843170836247
Minimum: 3
Maximum: 100

Sorted (Descending):
 [100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]

Indices of 3 largest values: [10  1 11]
Top 3 values: [ 88  93 100]


Section C — Pandas Basics

In [19]:
'''
7. Create a Pandas DataFrame from the dictionary below and perform the following:
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], "Age": [23, 21,
25, 22, 24], "Department": ["AI", "Data Science", "AI", "Web Dev", "Data
Science"], "Score": [88, 92, 79, 95, 67], }
a) Display the first 3 rows and the data types of each column.
b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').
c) Sort the DataFrame by Score in descending order.
d) Filter rows where Department is 'AI'.
''';

In [20]:
import pandas as pd

#
data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}


df = pd.DataFrame(data)

print("Original DataFrame:\n", df)


print("\nFirst 3 Rows:\n", df.head(3))
print("\nData Types:\n", df.dtypes)

df["Grade"] = ""

df.loc[df["Score"] >= 90, "Grade"] = "A"
df.loc[(df["Score"] >= 75) & (df["Score"] < 90), "Grade"] = "B"
df.loc[df["Score"] < 75, "Grade"] = "C"

print("\nDataFrame with Grades:\n", df)


sorted_df = df.sort_values(by="Score", ascending=False)
print("\nSorted by Score (Descending):\n", sorted_df)

# d) Filter Department = AI
ai_df = df[df["Department"] == "AI"]
print("\nAI Department Students:\n", ai_df)

Original DataFrame:
     Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

First 3 Rows:
     Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

Data Types:
 Name          object
Age            int64
Department    object
Score          int64
dtype: object

DataFrame with Grades:
     Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

Sorted by Score (Descending):
     Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79

In [21]:
'''
8. Using the same DataFrame from Q7:
a) Group by Department and find the average Score for each.
b) Find the row with the highest Score using idxmax().
c) Rename the column Score to Marks.
d) Drop the Age column and display the resulting DataFrame
''';

In [22]:
import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n", df)


dept_avg = df.groupby("Department")["Score"].mean()
print("\nAverage Score by Department:\n", dept_avg)


max_index = df["Score"].idxmax()
highest_score_row = df.loc[max_index]
print("\nRow with Highest Score:\n", highest_score_row)

df = df.rename(columns={"Score": "Marks"})
print("\nAfter Renaming Score to Marks:\n", df)


df = df.drop(columns=["Age"])
print("\nAfter Dropping Age Column:\n", df)

Original DataFrame:
     Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

Average Score by Department:
 Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64

Row with Highest Score:
 Name            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object

After Renaming Score to Marks:
     Name  Age    Department  Marks
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

After Dropping Age Column:
     Name    Department  Marks
0  Aarav            AI     88
1  Priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil  Data Science     67


In [23]:
'''9. Create a DataFrame with some missing values as shown below and handle them:
import numpy as np data = { "Product": ["Pen", "Notebook", "Eraser",
"Sharpener", "Ruler"], "Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50,
np.nan, 30, 20], }
a) Check the number of missing values in each column using isnull().sum().
b) Fill missing Price values with the column mean.
c) Drop rows where Stock is still missing.
d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index.
''';

In [25]:
import pandas as pd
import numpy as np


data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n", df)


print("\nMissing values in each column:\n", df.isnull().sum())


price_mean = df["Price"].mean()
df["Price"] = df["Price"].fillna(price_mean)

print("\nAfter filling missing Price:\n", df)


df = df.dropna(subset=["Stock"])

print("\nAfter dropping rows with missing Stock:\n", df)

df.to_csv("cleaned_products.csv", index=False)

print("\nCleaned data saved to 'cleaned_products.csv'")

Original DataFrame:
      Product  Price  Stock
0        Pen   10.0  100.0
1   Notebook    NaN   50.0
2     Eraser    5.0    NaN
3  Sharpener    8.0   30.0
4      Ruler    NaN   20.0

Missing values in each column:
 Product    0
Price      2
Stock      1
dtype: int64

After filling missing Price:
      Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2     Eraser   5.000000    NaN
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

After dropping rows with missing Stock:
      Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

Cleaned data saved to 'cleaned_products.csv'


In [27]:
'''
10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:
a) Print its shape and column names.
b) Add a new column Total_Value as Price multiplied by Stock.
c) Use describe() to print summary statistics of the numeric columns.
d) Wrap the file reading step in a try-except block to handle the case where the file does not
exist (FileNotFoundError).
''';

In [28]:
import pandas as pd

try:
  
    df = pd.read_csv("cleaned_products.csv")

    print("DataFrame Loaded Successfully\n")

   
    print("Shape of DataFrame:", df.shape)
    print("Column Names:", df.columns.tolist())

    df["Total_Value"] = df["Price"] * df["Stock"]

    print("\nDataFrame with Total_Value:\n", df)

   
    print("\nSummary Statistics:\n", df.describe())

except FileNotFoundError:
    print("Error: The file 'cleaned_products.csv' does not exist.")

DataFrame Loaded Successfully

Shape of DataFrame: (4, 3)
Column Names: ['Product', 'Price', 'Stock']

DataFrame with Total_Value:
      Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

Summary Statistics:
            Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
